# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-10-21 19:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20181014_2326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2018, 10, 21, 19, 21, 22, 727468, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
